### ISSUE TITLE
Latest Docker image does not work

### ISSUE THREAD

**Issue by sigmundv** [knonm/kotlin-notebook#9]
Hi,

When running the latest Docker image, the Kotlin kernel never starts, but returns the error below five times before finally failing. It looks to me like the image has been compiled with JDK 11 instead of JDK 8. The previous image works fine.

```text
[I 2023-03-20 20:46:53.705 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Listening for transport dt_socket at address: 1044
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:134)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:115)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:178)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:453)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:439)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.getLogger(logging.kt:9)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.getLogger$default(logging.kt:9)
	at org.jetbrains.kotlinx.jupyter.ConfigKt$log$2.invoke(config.kt:16)
	at org.jetbrains.kotlinx.jupyter.ConfigKt$log$2.invoke(config.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlinx.jupyter.ConfigKt.getLog(config.kt:16)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.main(ikotlin.kt:70)```

**Comment by knonm** [comment]
Thanks for the contribution, [sigmundv](https://github.com/sigmundv)!

I guess what happened here is that a bunch of libraries from `kotlin-jupyter` were updated (here https://github.com/Kotlin/kotlin-jupyter/commit/d908800f7f82cd9dd7d39c2d133d6b12261da502). Logback was updated from 1.2.x to 1.4.x, and since 1.4.x, Logback supports JDK 11+ (From Logback's website):
![image](https://user-images.githubusercontent.com/7424022/228942940-68158db6-23bb-465e-9b68-789adaa02609.png)
